### PR TITLE
Adds http polling to the front end to keep data updated #28.

### PR DESCRIPTION
**Pull request by brock8503**

### CODE REVIEW

**Comment by brock8503** [comment]
@eldang @mdunsmuir Introduction http polling to keep the data live. It definitely adds a new dynamic that we need to spend a lot more brain cycles on getting just right. A quick review would be nice, otherwise I am going to merge this by lunch and get the teams eyes on it reviewing.

**Comment by mdunsmuir** [comment]
Just from a quick read (and the subtleties of some of that JS are doubtless lost on me) this seems fine. Are you polling every 5 seconds? If so, we may want to change the backend's cache expiration time to be the same (rather than 1 minute, which is what it is now).

**Comment by mdunsmuir** [comment]
or we could do long polling or web sockets and let the backend decide :))))

**Comment by kd8drx** [comment]
Some stuff to consider:
 - Busses only update Metro every 90 seconds, so updating every 5 seconds is probably a bit much. Maybe doing an update every 10-15 seconds is more reasonable?

 - Remember that these kiosks are connecting to the web over a somewhat laggy ITS Band WiFi network (4.9 GHz) that can be a bit flaky if the conditions get wonky, meaning that the Wifi can drop for some time accidentally and kill the kiosks. Having a recovery mode is pretty important. I'll add a feature request for that.

**Comment by eldang** [comment]
I don't see any obvious issues except what @kd8drx has already raised, but there's no substitute for trying it out for real.

**Comment by eldang** [comment]
(in other words, let's merge and poke at it)

**Comment by brock8503** [comment]
Lets work on the configuration and architecture after demo day, I care more about experience for this one. Going to merge it in.

**Pull request merged**
